guerrero=Personaje con una gran poder de ataque y defensa. Es capaz de utilizar todas las armas físicas.

slime=Monstruo más débil de todos. Nació como una acumulación de magia. Carece de defensa física y posee una baja resistenca mágica.