espHierro=Espada de hierro básica. Inflige daño físico, que la defensa del enemigo puede prevenir.
violaSlimes=¿En cuantos hentai los slimes violan a las inocentes doncellas?/¡Pues con esta espada se acabó, porque hace el triple de daño si el enemigo es un Slime!
grimBasico=Grimorio básico. Inflige daño mágico, que la resistencia del enemigo puede prevenir.